export const dummyData = [
  {
    id: 0,
    name: "ssk.exe",
    profileImage: require("./assets/ProfileImages/shubham.png"),
    likes: "1,729",
    storyTapped: false,
  },
  {
    id: 1,
    name: "Aditya",
    profileImage: require("./assets/ProfileImages/aditya.png"),
    likes: "1,729",
    storyTapped: false,
  },
  {
    id: 2,
    name: "Amlan",
    profileImage: require("./assets/ProfileImages/amlan.png"),
    likes: "1,729",
    storyTapped: false,
  },
  {
    id: 3,
    name: "Adyasar",
    profileImage: require("./assets/ProfileImages/adyasar.png"),
    likes: "1,729",
    storyTapped: false,
  },
  {
    id: 4,
    name: "Gauri",
    profileImage: require("./assets/ProfileImages/gauri.png"),
    likes: "1,729",
    storyTapped: false,
  },
  {
    id: 5,
    name: "Prakhar",
    profileImage: require("./assets/ProfileImages/prakhar.png"),
    likes: "1,729",
    storyTapped: false,
  },
  {
    id: 6,
    name: "Pratiksha",
    profileImage: require("./assets/ProfileImages/pratiksha.png"),
    likes: "1,729",
    storyTapped: false,
  },
  {
    id: 7,
    name: "Preeti",
    profileImage: require("./assets/ProfileImages/preeti.png"),
    likes: "1,729",
    storyTapped: false,
  },
  {
    id: 8,
    name: "Rishabh",
    profileImage: require("./assets/ProfileImages/rishabh.png"),
    likes: "1,729",
    storyTapped: false,
  },
];
